package webscrape;

import java.util.*;

public class EmployeePolicyExamples {

    public ArrayList<ArrayList<String>> exampleList = new ArrayList<ArrayList<String>>();

    public EmployeePolicyExamples() {
        ArrayList<String> emplExample1 = new ArrayList<String>(Arrays.asList("The University recruits and hires faculty of the highest caliber to teach our students.  The process for compensating our faculty and recording their credentials must reflect the university’s high standards.  It is essential that our policies and processes are in compliance with both Southern Association of Colleges and Schools (SACS) accreditation requirements and Internal Revenue Service (IRS) regulations at all times. Faculty hired to teach for academic credit cannot be paid as Independent Contractors.  Faculty salaries must be paid through the university’s Payroll office. Faculty listed as “zero salary” may not be paid via invoice to third party consulting agencies.  They must be paid in one-time payments through the university’s Payroll office. ".split("\\s")));
        exampleList.add(emplExample1);
        ArrayList<String> emplExample2 = new ArrayList<String>(Arrays.asList("Consistent with this goal, the University will not employ individuals or appoint unpaid affiliates with prior criminal convictions or driving records (when applicable) who are determined to pose an unacceptable safety risk to the University or its employees, students and visitors. The University’s background check process is intended to identify the presence of any such circumstances and to provide a basis for making good faith and sound determinations as to whether such matters rise to the level barring appointment. A background check must be satisfactorily completed prior to employment or appointment.".split("\\s")));
        exampleList.add(emplExample2);
        ArrayList<String> emplExample3 = new ArrayList<String>(Arrays.asList("Consistent with the University research, teaching and public service missions, the University encourages faculty, staff and students to engage in appropriate outside relationships with private industry and the nonprofit sector. But members of the University community are expected to avoid conflicts of interest or commitment that have the potential to directly and significantly affect the University’s interests, compromise objectivity in carrying out University responsibilities, or otherwise compromise performance of University responsibilities, unless such conflicts are disclosed, reviewed, and managed in accordance with this Policy. This Policy on Individual Conflicts of Interest and Commitment (hereinafter, the “Policy”) describes the University’s approach and process for identifying, reviewing, and managing such relationships to help assure the integrity of University academic and administrative endeavors.".split("\\s")));
        exampleList.add(emplExample3);
        ArrayList<String> emplExample4 = new ArrayList<String>(Arrays.asList("Academic freedom is the right of a faculty member to be responsibly engaged in efforts to discover, speak and teach the truth. It is the policy of the University to maintain and encourage full freedom, within the law, of inquiry, discourse, teaching, research, and publication and to protect any member of the faculty against influences, from within or without the University, which would restrict the faculty member in the exercise of these freedoms in his or her area of scholarly interest.".split("\\s")));
        exampleList.add(emplExample4);
        ArrayList<String> emplExample5 = new ArrayList<String>(Arrays.asList("Twelve-month faculty members are entitled to 24 days of annual leave per calendar year. Nine-month faculty do not earn either annual or sick leave. They are eligible for paid serious illness and parental leave. For more information on this policy, click here. Both nine- and twelve-month faculty generally observe the same holidays as other University employees except that when classes are scheduled during a normal university holiday, faculty are expected to work when assigned teaching duties. Employees should refer also to the Family Illness Leave, Voluntary Shared Leave, and Leave without Pay policies. EPA Faculty employees should refer also to the Faculty Serious Illness, Major Disability and Parental Leave Policy. When an employee is on paid or unpaid leave but has not given notice of the need for FMLA leave, the department shall, after a period of 10 workdays, request that the employee provide sufficient information so the Medical Leave Coordinator in Benefit Services can establish whether the leave is for a FMLA-qualifying reason. This requirement does not preclude the department from requesting the information sooner.".split("\\s")));
        exampleList.add(emplExample5);
        ArrayList<String> emplExample6 = new ArrayList<String>(Arrays.asList("Half-time salary is one-half of a faculty member’s base salary for the fiscal year immediately preceding the fiscal year in which the Phased Retirement Plan is implemented for that individual. It does not include supplements for administrative assignments, overloads, or similar payments to which the faculty member is not legally entitled. For the School of Medicine full-time tenured faculty subject to the terms of the Clinical Faculty Compensation Plan, a faculty member’s \"base compensation\" under the Phased Retirement Plan shall be that individual’s Total Projected Salary (Academic Base Salary + Negotiated Component of Salary + estimated Bonus Salary) for the fiscal year immediately preceding the fiscal year in which the Phased Retirement Plan is implemented for that individual.".split("\\s")));
        exampleList.add(emplExample6);
    }

}